---
- name: Server and client are installed
  yum:
    name: postgresql, postgresql-server, python-psycopg2
    state: installed

- name: Default Db is initalized
  shell: service postgresql initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf

- name: Server is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create user {{ postgres_user }}
  postgresql_user: 
    name: '{{ postgres_user }}'
    password: '{{ postgres_pass }}'
  become_user: postgres

- name: Databases are created by {{ postgres_user }}.
  postgresql_db: 
    name: '{{ item.dbname }}'
    owner: '{{ postgres_user }}'
  with_items:
  - '{{ postgres_dbs }}'
  become: true
  become_user: postgres

- name: Grant ALL to {{ postgres_user }}
  postgresql_privs:
    database: '{{ item.dbname }}'
    roles: '{{ postgres_user }}'
    type: database
    priv: ALL
  with_items:
  - '{{ postgres_dbs }}'
  become_user: postgres

- name: '{{ postgres_user }} is allowed to connect to db'
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    insertbefore: '^# "local"'
    state: present
    line: '{{ item }}'
  with_items:
  - 'local all {{ postgres_user }} md5'
  - 'host all {{ postgres_user }} 127.0.0.1/32 md5'
  register: postgresql_config

- name: Restart postgresql server after configration change
  service:
    name: 'postgresql'
    state: 'restarted'
  when: postgresql_config.changed
