- name: epel-release installed
  yum:
    name: epel-release
    state: installed

- name: install LXC
  yum:
    name: debootstrap, perl, libvirt, lxc, lxc-templates
    state: installed

- name: install vagrant
  yum:
    name: https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.rpm
    state: installed

- name: install LXC support for vagrant
  shell: vagrant plugin install vagrant-lxc
